### ISSUE TITLE
`sdl2-config-mac` doesn't support brew (was ビルドできませんでした)

### ISSUE THREAD

**Issue by edama2** [umjammer/quasi88-sdl2#1]
実行環境 macos 10.14.6
brew install sdl2をした後、makeしたんですがエラーが出てビルドできませんでした

`
ld: warning: option -s is obsolete and being ignored
ld: framework not found SDL2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [quasi88.sdl2] Error 1
`

**Comment by umjammer** [comment]
have you try `sdl2-config-mac` and results indicate correct location?

```shell
$ pwd
/foo/bar/quasi88-sdl2
$ ./osx/sdl2-config-mac --libs
-F/Library/Frameworks -framework SDL2
$ ./osx/sdl2-config-mac --cflags
-I/Library/Frameworks/SDL2.framework/Headers -I/opt/X11/include -D_THREAD_SAFE
```

in my case results indicate the frameworks location.

you use brew, so modification the Makefile like below might make you happy.

```diff
diff --git a/Makefile b/Makefile
index 777a6a2..126ffa6 100644
--- a/Makefile
+++ b/Makefile
@@ -278,7 +278,7 @@ SOUND_SDL2          = 1
 SDL_CONFIG     = sdl-config
 
 ifeq ($(ARCH),macosx)
-SDL2_CONFIG    = ./osx/sdl2-config-mac
+SDL2_CONFIG    = sdl2-config
 else
 SDL2_CONFIG    = sdl2-config
 endif
```

**Comment by edama2** [comment]
Thank you!
